### ISSUE TITLE
Re-establish support for PHP 7.2

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#1207]
Revert #1111.

**Comment by JakeQZ** [comment]
We can mark all EOL versions of PHP as deprecated, indicating that support/comatibility may be removed in a future major release, without actually removing such support in the next major release if there is no reason for us to do so.  (Buyer beware - but hosting many websites through a single version of PHP [as most website hosting companies require], I can tell you that an enforced PHP upgrade actually prevents an upgrade, because some sites are not ready and/or have not been tested against the lastest PHP, and if I don't have time to do the testing and due diligence against the latest version, then nothing can be updated.)

**Comment by JakeQZ** [comment]
Just realized that `willnotimplement` should be `wontimplement`, to be consistent with `wontfix`.  Guess you can just rename the lable - ?

**Comment by oliverklee** [comment]
Thanks, done.
