### ISSUE TITLE
Drop support for Symfony 4.4

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#1242]
https://symfony.com/releases

**Comment by JakeQZ** [comment]
I don't think we should do this until we need to, e.g. because we need a new feature or bugfix.

I made a similar argument against dropping support for 'unsupported' PHP versions until we have to.  (Can't find the main discussion about that, which isn't referenced from #1207.  In that case you tried to re-established support for PHP 7.2, but we found we did actually need to ditch it after all.)

Main point is that it's not for us to force users to upgrade third party components if there are no known compatibility issues with the older versions.  We've thoroughly tested against these older versions, through each iteration or both our software and theirs, which is more than can be said for the latest version of a third-party component.

'Unsupported' does not mean 'broken'.  It just means that the developers have chosen to save resources by not merging any more bug fixes to a previous release branch - which is understandable: as the code deviates, such merges become more and more time-consuming and error-prone.

I've had situations where Composer cannot satisfy dependencies due to chains of minimum and maximum version dependencies leading to one component needing a later version of a dependency than the latest allowed by some other component.  I'd rather avoid inflicting that problem on our users unnecessarily.

On that basis, which we've discussed before, I'm moving this to a future milestone.

**Comment by JakeQZ** [comment]
Also worth noting that some developers do apply security vulnerability fixes to unsupported versions.  E.g. WordPress [released 4.1.39 on 12 October 2023](https://wordpress.org/download/releases/#branch-41), almost 9 years after the initial 4.1 release.  They don't use semver, so the latest 6.4 is 23 major releases ahead.  [The latest PHP version supported by WordPress 4.1.39 is PHP 5.6](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/).

**Comment by oliverklee** [comment]
From https://github.com/MyIntervals/emogrifier/pull/1278#issuecomment-2440153293:

> I propose we skip the unit tests on CI for PHP 8.4 with the lowest dependencies (so we can release version 7.3.0) and drop support for Symfony 4.4 in version 8.0.0.
