### ISSUE TITLE
Move `CONTRIBUTION.md` to the project root

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#1284]

**Comment by JakeQZ** [comment]
GitHub doesn't seem to make it easy to find the contribution guidelines.  From [the documentation](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors):

> When someone opens a pull request or creates an issue, they will see a link to that file.

I tested this.  You only seem to get a pop-up with a link if the file has changed since your last visit.  It is too easy to dismiss the pop-up and no longer have an easy means of accessing the file.

> The link to the contributing guidelines also appears on your repository's contribute page.

I cannot see any link to a "contribute" page anywhere on a repository's home page.  I looked at CssSelector, in case I got a different view for a repository on which am a colloborator.  There are links for Readme (which is displayed anyway), Licence, Code of Conduct, and Security Policy.  But nothing for Contributing.  CssSelector's readme begins with an 'Additional Resources' section including a link to their contribution guidelines.  So it seems we are doing something like what they are to help people find it.  But I am wondering how and where to find this mysterious "contribute page".

**Comment by JakeQZ** [comment]
> But I am wondering how and where to find this mysterious "contribute page".

There is a page at https://github.com/github/docs/contribute which has a link to GitHub's contribution guidelines.  But I can't see any link to that from [GitHub's own repository page](https://github.com/github), and the equivalent URL for other repositories (CssSelector, Emogrifier) results in a 404 error.

**Comment by oliverklee** [comment]
We could additionally create issue/PR templates and link the document from there: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
