### ISSUE TITLE
Use Symfony CSS selector component

### ISSUE THREAD

**Issue by bramley** [MyIntervals/emogrifier#287]
I came across this Symfony component for converting css selectors to xpath https://github.com/symfony/css-selector and wondered whether it has previously been considered?

I would expect it to be much more complete than the current Emogrifier and probably more robust too.

I have made  a simple change to use it instead of the code in method translateCssToXpath() and almost all unit tests pass. Those that fail seem to highlight bugs in the current Emogrifier code, such as https://github.com/jjriv/emogrifier/issues/286

Would all unit tests passing be sufficient assurance for the component to be used?

**Comment by oliverklee** [comment]
Hi @bramley, great suggestion!

I'd like use to first get the bugs in the behavior fixed so that we can start with a green bar (so to speak) and then use these tests to make sure that using the Symfony component does not break anything.

Particularly, I think we should tackle these bugs/tickets first:
#284
#286 
#287

Would you be willing to help?

(And I'll also take care of reviewing, polishing and merging of #250 and #283.)

**Comment by wimulkeman** [comment]
@oliverklee I submitted a issue https://github.com/jjriv/emogrifier/issues/356 which could be fixed with the usage of the Symfony CSS Selector. I would love to see the inclusion of this selector component getting through.
