### ISSUE TITLE
Update PHPUnit and use expectException in the tests

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#438]

**Comment by zoliszabo** [comment]
Hi @oliverklee!

There is the issue that PHPUnit's `expectException()` is available since version 5.2 of PHPUnit (https://github.com/sebastianbergmann/phpunit/blob/5.2.12/src/Framework/TestCase.php#L505), which requires PHP 5.6+ (https://github.com/sebastianbergmann/phpunit/blob/5.2.12/composer.json#L24). But emogrifier supports also PHP 5.5, so we cannot make the upgrade of PHPUnit to 5.2.

Alternatively, we could use `setExpectedException()`. The only problem is that it got deprecated in favor of `expectException()` since 5.2.

What should we do?

**Comment by oliverklee** [comment]
Oh, I hadn't thought of that. Then let's stay with `@expectedException` until Emogrifier requires PHP 5.6.
