### ISSUE TITLE
Installation without Composer

### ISSUE THREAD

**Issue by bigweld86** [MyIntervals/emogrifier#564]
Hello. Is it possible to install without composer. If so, can you please share the steps? Thanks

**Comment by oliverklee** [comment]
Yes, just download the files, e.g., using the green "Clone or Download" button at https://github.com/MyIntervals/emogrifier, and then `include` the file `src/Emogrifier.php` in your PHP code. That's it! :-)

**Comment by oasiz** [comment]
Hi, hope you're well.

Sorry to drag up such an old 'issue' but I just wondered if this was still the case for those not using Composer?

I get the following error when just including/requiring the CssInliner.php file:

`Fatal error: Uncaught Error: Class 'Pelago\Emogrifier\HtmlProcessor\AbstractHtmlProcessor' not found in /home/ewecuouu/php/Pelago/Emogrifier/src/CssInliner.php:16`

**Comment by oliverklee** [comment]
@oasiz No, Emogrifier does not support installation without Composer anymore. Version 3.1.0 should be the last version that works without Composer. You can use that version, but we do not support non-Composer usage after that. (And there will also be no maintenance releases for version 3.x anymore. So you're on your own with that.)

I strongly recommend to always use Composer for your projects. Otherwise, you will get into all kinds of problems when working with libraries.

If you really cannot use Composer directly, you can put a `composer.json` that requires Emogrifier in a directory and then include Composer's `autoload.php` in your code. We do it here:
https://github.com/oliverklee/ext-oelib/tree/main/Resources/Private/Php
https://github.com/oliverklee/ext-oelib/blob/main/Classes/Email/Mail.php#L262

**Comment by oasiz** [comment]
Thanks for the fast and informative response! Shall look further into composer.

Thanks again :-)

**Comment by JakeQZ** [comment]
Hi @oasiz,

It is actually still possible to use Emogrifier without Composer, but you would either need to provide an autoloader, or `require_once` all of the class files within the `src` directory.  To provide an autoloader, you can use something like the following instead of `require_once __DIR__ . '/emogrifier/src/CssInliner.php'`:

```php
\spl_autoload_register(function($class) {
    $prefix = \strtok($class, '\\');
    if ($prefix === 'Pelago') {
        $path = \str_replace(['Pelago\\Emogrifier', '\\'], ['Emogrifier/src', '/'], $class) . '.php';
        include_once __DIR__ . '/' . $path;
    }
});
```

I haven't actually tested this specific autoloader incarnation (there may be typos, etc.), but can't think of a reason why it shouldn't work in principle.  HTH and you get the idea.

(If on shared hosting without SSH access, using Composer can be awkward.)

**Comment by JakeQZ** [comment]
> It is actually still possible to use Emogrifier without Composer (AFAIAA)

Sorry, I have realized this is not great advice.  Emogrifier now depends on the [Symfony CssSelector package](https://github.com/symfony/css-selector) so you would also need to download that and set up an autoloader for its classes.  And if that depends on any other packages (according to its `composer.json` it doesn't), the same for those tertiary dependencies.

Thus it's still possible to not use Composer, but not straightforward or recommended.  You would be basically having to manually perform the tasks Composer does for you.

**Comment by oliverklee** [comment]
Please note that you'll only need a Composer installation for _creating_ the Composer autoload data (i.e., `vendor/autoload.php`). You do not need to have Composer installation for _using_ the created autoload data. (That's what I do in the oelib library package.) So there's no need to re-implement the autoloading wheel. ;-)
