### ISSUE TITLE
Support PHP 7.2 in version 1.2.x

### ISSUE THREAD

**Issue by chrisdeeming** [MyIntervals/emogrifier#580]
My dev environment typically uses the most up to date PHP version available, though the application we develop actually requires a minimum of PHP 5.4 currently so we have to use v1.2.0. To avoid introducing code that is not compatible, I develop with the language level set to PHP 5.4 in my IDE.

However, because the composer.json file for v.1.2.0 requires `"php": ">=5.4.0,<=7.1.99"` every time I add or update our composer dependencies, the emogrifier dependency prevents this, and I have to downgrade to PHP 7.1 in order to perform this task and revert back to PHP 7.2.

So a few of questions:

1) Is there confirmed issues with emogrifier v1.2.0 and PHP 7.2?
2) If not, can we update composer.json to remove this restriction (or at least change it to `"php": ">=5.4.0,<=7.2.99"` until compatibility with PHP 7.3 is confirmed)
3) If there are confirmed issues, would you be open to me submitting a pull request to resolve them, and releasing that as v1.2.1?

FWIW, the only reason I haven't dived into the code, yet, is because I believe there might not actually be any compatibility issues, so it would just involve updating the composer.json file accordingly. The reason I say this is because we actually have nearly 12% of our customer base (who are using a version of our software that contains emogrifier) who are using PHP 7.2 (with emails being a fairly core component in our application) and there have been no reported issues so far.

So, ultimately, if this is just a case of being cautious or unsure about compatibility and there are no known issues (I will be happy to do some more detailed testing to 100% confirm that, though) then I think we're safe to remove that requirement.

**Comment by oliverklee** [comment]
Hi @chrisdeeming, Emogrifier 1.2.x is not supported anymore. However, I've created a branch `1.2.x` for you to create a pull request against if you like. Please also add PHP 7.2 to the Travis CI build matrix so we can be sure things work correctly.

I don't know of any issues with Emogrifier 1.2.0 running under PHP 7.2. But then again, I have never used that version with PHP 7.2. :-)

By the way, which software is it that you're working on that should support such a wide range of PHP versions (5.4-7.2)?

`<personal opinion>`
1. If you are creating software that should work with PHP >= 5.4.0, I recommend actually running PHP 5.4 for local development so the code will not have anything that requires a newer PHP version.

2. Unless this is really business-relevant and the reaped benefit really justifies the additional effort and the loss of modern PHP features, I recommend not supporting PHP 5.4 in current releases of 
packages. People who insist on using an outdated PHP version that has not been getting any security fixes for years can use an old version of the package that still supports PHP 5.4. (I think that if people don't care about security, using features as an incentive to upgrade to secure PHP versions is a good thing.)

`</personal opinion>`

**Comment by JakeQZ** [comment]
I've been involved with Emogrifier since 1.2.0 and don't recall any changes specifically addressing PHP 7.2 issues.

As Composer doesn't install PHP, and PHP 7 should be fairly settled now, it may be wiser to make the requirement `... || ^7.0` or `... <=7.99` to avoid pointlessly revisiting this issue.

PHP 7 adoption is strong now, aided by pushing by hosting providers having realized it will save them resources.  If only the same were true at the client end, where some IT departments are still maintaining IE6 and Outlook 1970...

**Comment by oliverklee** [comment]
Please let's keep the PHP version requirements to `~7.x`, not `^7.x` (i.e., we'll to add new PHP feature releases when they come up). I'd prefer this because we make a statement about the compatibility with PHP versions, and people will rely on that and might get breakage if we don't do this well.

I'm willing to create short-terms bug-fix releases that add PHP version compatibility.

**Comment by chrisdeeming** [comment]
Sorry for the delay with this. In my testing it all seems ok and Travis seems to be passing so it really was just a case of moving the version constraints.

**Comment by oliverklee** [comment]
Closed via 24de2b3e7ace82560ab25b57c9b42531e31cad40.
