### ISSUE TITLE
composer update fails for PHP version < 7

### ISSUE THREAD

**Issue by zoliszabo** [MyIntervals/emogrifier#585]
It looks like Travis CI builds fail now, because `composer update` won't install packages anymore for PHP versions smaller than 7.0.

Log of the latest successful run of the Travis build:
https://travis-ci.org/MyIntervals/emogrifier/jobs/365757072#L516

Currently failing build log:
https://travis-ci.org/MyIntervals/emogrifier/jobs/388365600#L506

Please observe the difference how now it says `No dependencies installed. Try running composer install or update.`, even if `slevomat/coding-standard` could not be installed in both cases.

Not sure what the issue might be, the only difference seems to be the version of composer (1.6.3 vs 1.6.5), but I have the same problem on my localhost even with 1.6.3.

**Comment by JakeQZ** [comment]
I'm also seeing it fail with 1.6.3 locally.  I think it had succeeded before because it was not starting with a clean system, and the dependencies and autoload files were already present from a previous build, e.g. in https://travis-ci.org/MyIntervals/emogrifier/jobs/364877259 before #576 we see

> Nothing to install or update
> Writing lock file
> Generating autoload files

whereas in https://travis-ci.org/MyIntervals/emogrifier/jobs/365752325 after that change we don't see this in the composer output, but instead the error message.  In both cases the list of packages follows, but in the latter I think it is only because they were _already_ installed before Composer ran.

I'm trying to find a way to tell composer that a package is only required for (say) PHP>=7, but to no avail so far.  There is `--ignore-platform-reqs` (https://github.com/composer/composer/pull/3320) but that is no good as it causes the PHP version to be completely ignored, and for every single package.  Maybe we would need to provide a separate composer.json for PHP 5 in Travis but that would be an ugly solution.

**Comment by zoliszabo** [comment]
> I'm also seeing it fail with 1.6.3 locally. I think it had succeeded before because it was not starting with a clean system, and the dependencies and autoload files were already present from a previous build, e.g. in https://travis-ci.org/MyIntervals/emogrifier/jobs/364877259 before #576 we see
>
>   > Nothing to install or update
>   > Writing lock file
>   > Generating autoload files
>
>whereas in https://travis-ci.org/MyIntervals/emogrifier/jobs/365752325 after that change we don't see this in the composer output, but instead the error message. In both cases the list of packages follows, but in the latter I think it is only because they were already installed before Composer ran.

You're right.

>  Maybe we would need to provide a separate composer.json for PHP 5 in Travis but that would be an ugly solution.

Or we remove the `slevomat/coding-standard` dev-dependency from composer.json and use `composer require --dev slevomat/coding-standard` directly from .travis.yml, only when `composer ci:php:sniff` is also executed (PHP version >= 7).
We could even execute both `ci:php:md` & `ci:php:sniff` only once (like you also suggested here: https://github.com/MyIntervals/emogrifier/pull/576#issue-180923569).
Am I thinking this correctly?

**Comment by oliverklee** [comment]
> Or we remove the slevomat/coding-standard dev-dependency from composer.json and use composer require --dev slevomat/coding-standard directly from .travis.yml, only when composer ci:php:sniff is also executed (PHP version >= 7).

Yes, let's do that.

> We could even execute both ci:php:md & ci:php:sniff only once (like you also suggested here: #576 (comment)).

I'm fine either way.

**Comment by JakeQZ** [comment]
> Or we remove the slevomat/coding-standard dev-dependency from composer.json and use composer require --dev slevomat/coding-standard directly from .travis.yml, only when composer ci:php:sniff is also executed (PHP version >= 7).

Yes, that would work.  It does overwrite composer.json so I'd hope the next Travis build running from the same directory would restore its original content (if it doesn't, the result would be as in the previous builds which succeeded despite Composer failing to update previously installed packages to the desired versions).

**Comment by oliverklee** [comment]
We can restore the `composer.json` after the `composer require`, e.g., like this: https://github.com/helhum/ext_scaffold/blob/master/.travis.yml#L26

**Comment by oliverklee** [comment]
(We'd then have to remove the `composer validate`, but that's okay.)
