### ISSUE TITLE
Stylesheet in body seems to be ignored by gmail

### ISSUE THREAD

**Issue by TwanVermeulen** [MyIntervals/emogrifier#634]
I'm currently working on a responsive email design. I don't get the media queries to work correct in gmail while using v2.0 of emogrifier. If I use the older version (1.2.1), it seems to work fine. 

I think it's related to (https://github.com/MyIntervals/emogrifier/pull/396), since all style blocks are automatically moved to the body. I think gmail automatically ignores those stylesheets. 

Is anyone aware of this issue? Or am I missing something here. I would like to use the latest version of this lib if possible.

Thanks for you help!

**Comment by oliverklee** [comment]
Hi @TwanVermeulen, as far as I know, nobody has been aware of this issue so far. Would you be willing to debug this further and find out the root cause? Thanks!

**Comment by zoliszabo** [comment]
I can confirm. This is something we overlooked.

After a quick search, several sources say (e.g. [emailonacid]((https://www.emailonacid.com/blog/article/email-development/12_things_you_must_know_when_developing_for_gmail_and_gmail_mobile_apps-2/#gmail_tip4)) that, indeed, Gmail strips out `<style>` elements embedded in the `<body>`.

Also did a quick test myself, which confirms this.

As a workaround (and this is how I actually use Emogrifier in real code), CSS blocks that contain media queries can be separated from the whole CSS and embedded directly into the `<head>` of your HTML email document. Since media queries cannot be inlined anyway, there's no real reason to pass them through Emogrifier.

This needs to be corrected though... ASAP.

**Comment by TwanVermeulen** [comment]
OK, let me get back to you

On Dec 8, 2018 18:16, "Zoli Szabó" <notifications@github.com> wrote:

I can confirm. This is something we overlooked.

After a quick search, several sources say (e.g. emailonacid that, indeed,
Gmail strips out <style> elements embedded in the <body>.

Also did a quick test myself, which confirms this.

As a workaround (and this is how I actually use Emogrifier in real code),
CSS blocks that contain media queries can be separated from the whole CSS
and embedded directly into the <head> of your HTML email document. Since
media queries cannot be inlined anyway, there's no real reason to pass them
through Emogrifier.

This needs to be corrected though... ASAP.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MyIntervals/emogrifier/issues/634#issuecomment-445474861>,
or mute the thread

**Comment by zoliszabo** [comment]
Foundation for Email documentation seems to be really lagging behind on how and what current email clients are able to do.

From https://foundation.zurb.com/emails/docs/css-guide.html#inlining:
> Email clients like Gmail and Outlook strip out <style> tag from the <head> and Gmails strips it from the <body> of the email as well. It's best to have your CSS written inline within your markup. Hand writing all your CSS inline in a style tag would be a real pain and would take a long time.

This is absolutely not true!

On the page of their online inliner tool:
> Positioning media query CSS: CSS inside a @media block can't be inlined, so it's put in a <style> tag. Because some clients, such as Outlook and Gmail, strip out any CSS found in the <head>, the inliner moves the <style> tag out of the <head> and into the <body>.

Also not true. And their online inliner tool really behaves like described, i.e. puts `<style>` in body.

I took the time to set up the Zurb's email template stack to test their latest version (followed instructions from https://github.com/zurb/foundation-emails#getting-started).
And the result was... that the `<style>` element was put in the `<head>` element.
You can also see [here in the code](https://github.com/zurb/foundation-emails-template/blob/master/src/layouts/index-layout.html) that the `<!-- <style> -->` placeholder is in the `<head>`.

> I don't know if there actually are any email clients that ignore CSS in the head but honour it in the body... If there are, it might be necessary to put the style in both the head and body!

According to https://www.campaignmonitor.com/css/style-element/style-in-head/ vs https://www.campaignmonitor.com/css/style-element/style-in-body/ there is only 1 email client that supports `<style>` in `<body>`, but not in `<head>` - the _Yahoo! Mail Android app_. Tested it, it's true.

I would vote for _not_ duplicating `<style>` blocks, at least not by default. For example in my use-case only 0.07% of the subscribers has an @yahoo email. Because of them, I'd rather not send duplicated code to all other 99.93%.

**Comment by oliverklee** [comment]
I'm for keeping it simple: Move the `style` element back into the `head`, and if someone complains, add an option to duplicate it. And then let's release a quick 2.1.1 with this change.

**Comment by JakeQZ** [comment]
> I'm for keeping it simple: Move the style element back into the head, and if someone complains, add an option to duplicate it. And then let's release a quick 2.1.1 with this change.

Ok.

**Comment by dinesh-19** [comment]
@zoliszabo could please you give an example of your workaround on this. Since we can't upgrade to the latest version right I need to do some quick fixes for our template. 

Thanks.
