### ISSUE TITLE
Emogrifier turns {} into %7B and %7D

### ISSUE THREAD

**Issue by Johnny99211** [MyIntervals/emogrifier#646]
I'm currently setting up an email template which has two parts: The HTML and the CSS. To put everything together and merge the HTML with the CSS I'm using the PHP Emogrifier.

Now I've found out that when I emogrify the two elements that there is a problem with the uft-8 encoding.

All works like Ä, Ü, Ö are correctly displayed but when I put a link like this here into the content, the utf-8 encoding don't works for this element:

Before emogrify:

> `<a href="{password_reset_link}" id="button">Passwort zurücksetzten</a>`

After emogrify:

>     <a href="%7Bpassword_reset_link%7D" id="button" style="color: #69f0ae; text-decoration: none; font-size: 20px; text-align: center; display: block; line-height: 1.7em !important; padding: .3em 1em;
>     > border: 2px solid #69f0ae; border-radius: 3px; -webkit-border-radius:
>     > 3px; -moz-border-radius: 3px; width: 40%; margin: auto; cursor:
>     > pointer !important;">Passwort zurücksetzten</a>

So as you can see the href is broken which is set with a placeholder which gets replaced with the correct link after the emogrify process:

    %7Bpassword_reset_link%7D

**Comment by zoliszabo** [comment]
_This is not a UTF-8 encoding issue, but the correct representation (encoding) of a href attribute._

Depending on how you replace your template variables (placeholders), one quick solution would be to also encode the placeholder before the replace:

```php
str_replace(rawurlencode('{placeholder}'), 'https://any.url.here');
```

**Comment by Johnny99211** [comment]
This is a bug in the emogrifier. I'm replacing the placeholder after the emogrify process but the placeholder is broken after merge css to the html with the help of emogrifier: https://github.com/MyIntervals/emogrifier/issues/98

**Comment by Johnny99211** [comment]
I've temporarily fixed it with this workaround after the emogrify process but in my eyes this is a bug which needs to be fixed:

```
//Apply CSS styles inline for picky email clients.
try {
	$emogrifier = new Emogrifier( $message, $css );
	$message    = $emogrifier->emogrify();
} catch ( Exception $e ) {
	$logger = wc_get_logger();
	$logger->error( $e->getMessage(), array( 'source' => 'emogrifier' ) );
}
$message = str_replace( array( '%7B', '%7D' ), array( '{', '}' ), $message );
```

**Comment by zoliszabo** [comment]
> This is a bug in the emogrifier. I'm replacing the placeholder after the emogrify process but the placeholder is broken after merge css to the html with the help of emogrifier: #98

Please note that Emogrifier uses [DOM](http://php.net/manual/en/book.dom.php) to work with HTML and the encoding we are talking about in this thread is a direct result of [DOMDocument::saveHTML()](http://php.net/manual/en/domdocument.savehtml.php). Please check here: [DOMDocument::saveHTML() behaviour example](http://sandbox.onlinephpfunctions.com/code/3be3685bc7bf1b86f3f956e1e82380a219c1b0a7).

You are right that this behaviour is messing up template variables, just like #98 also described this behaviour and it seems there was a solution (#170) for it back then, but apparently that code was removed from the code since then.

We will revisit this in the future... to make preserving template variables more straightforward with Emogrifier.

Thank you for your feedback!

**Comment by oliverklee** [comment]
For the record, my educated guess is that for href attributes, the value is expected to be a URL, that `DOMDocument::saveHTML()` properly URL-encodes the URL again. So I'm not sure there is a clean way of fixing/breaking this in Emogrifier (depending on whether creating URLs that are not properly encoded are considered a bug or a feature).

**Comment by zoliszabo** [comment]
> 
> 
> For the record, my educated guess is that for href attributes, the value is expected to be a URL, that `DOMDocument::saveHTML()` properly URL-encodes the URL again. So I'm not sure there is a clean way of fixing/breaking this in Emogrifier (depending on whether creating URLs that are not properly encoded are considered a bug or a feature).

Yes, this is exactly what I was trying to describe above. It is definitely not a bug from Emogrifier, since this behaviour is inherited from `DOMDocument` and it actually is the right way to do it.

However, given the fact that in many cases Emogrifier is used in a combination with some sort of templating system (which may use URL-encodable characters as template variable delimiters), we should see whether there would be some straightforward solution to not "break" these template variables during processing.

**Comment by oliverklee** [comment]
Maybe we can add some `HtmlProcessor` subclass that has two new methods: `renderWithTemplateMarkers` and `renderBodyWithTemplateMarkers` that take a string of characters that should not be URL-encoded (i.e., for which the URL-encoded variant will be replaced with the verbatim characters), having some characters as default value for that parameter.

What do you think?

**Comment by JakeQZ** [comment]
> Maybe we can add some HtmlProcessor subclass that has two new methods: ...

Architecturally this seems ok.  In terms of implementation, there are a couple of possible approaches that may be viable and would avoid needing to specify which characters should not be URL-encoded:

1. Before calling `saveHTML()`, replace all `href` attributes with a uniquely-named attribute with the same value, e.g. `data-emogrifier-href`; then a `str_replace()` can be applied to the result to change these back to `href` (provided the chosen attribute name would not otherwise occur in text nodes or attribute values).
2. Use `saveXML()` (or `save()`) rather than `saveHTML()` then remove the processing instruction and perform any other conversions required to achieve the same result.

I don't know if this feature affects other attributes, such as `src` in `img`, or what happens if the attribute value is already correctly percent-encoded.

**Comment by kaaaaaaaaaaai** [comment]
i have same problems

**Comment by oliverklee** [comment]
> I think we should close this, for that reason, and mention it in the caveats in the readme.

Agreed. Would you be willing to add this to the README, @JakeQZ ?

**Comment by JakeQZ** [comment]
> > I think we should close this, for that reason, and mention it in the caveats in the readme.
> 
> Agreed. Would you be willing to add this to the README, @JakeQZ ?

Will do.  For now have added #1247 to capture this.
