### ISSUE TITLE
Emogrifier adds tags but never closes them

### ISSUE THREAD

**Issue by drnkwati** [MyIntervals/emogrifier#677]
Hi 
If I provide an html source with missing tag whose style is present, the compiler creates the tag but never closes it.
Example:
```
HTML:
<div>simple</div>

SCSS:
.body {
.max-width: 100%;
}

RESULT:
<body style="max-width: 100%"><div>simple</div>
```

If I run the above code the compiler will add an HTML body with the provides style but never closes the body;
Is this expected if not how can we turn this behavior off

thanks

**Comment by oliverklee** [comment]
Hi @drnkwati, thanks for the bug report. I think your code snippets are not complete. Could you please update them and use triple backticks for code highlighting like this?

```html
<p>Hello world</p>
```

Thanks!

**Comment by JakeQZ** [comment]
I can reproduce this.  The issue is with `emogrifyBodyContent` when the `body` element has attributes (in this case it has a `style` attribute).  (The internal method `renderBodyContent` strips the `<body>` and `</body>` tags with a simple `str_replace`, and thus fails to remove the opening tag when it has attributes.)

Possible workarounds:
- Remove any CSS rules that apply to the `body` element (when using `emogrifyBodyContent`, any such rules are superfluous, as only the content of the `body` element is returned, not the element itself);
- Use `emogrify` rather than `emogrifyBodyContent` (if there is no particular reason not to want the full HTML including a doctype and the `html`, `head` and `body` container elements).

```php
    /**
     * Issue 677
     *
     * @test
     */
    public function emogrifyBodyContentWithCssRuleForBodyReturnsBalancedBodyTags()
    {
        $this->subject->setHtml('<div>simple</div>');
        $this->subject->setCss('body { max-width: 100%; }');

        $result = $this->subject->emogrifyBodyContent();

        self::assertThat(
            $result,
            self::logicalOr(
                self::logicalNot(self::stringContains('<body')),
                self::stringContains('</body>')
            )
        );
    }
```

**Comment by oliverklee** [comment]
@JakeQZ @zoliszabo Is any of you planning to work on this during the next few days? Otherwise, I'd like to move this bug to a later milestone so we can get 2.2.0 out of the door soon.

**Comment by JakeQZ** [comment]
> Is any of you planning to work on this during the next few days?

I may have time as it is a fairly straightforward fix...
