### ISSUE TITLE
CssInliner in release 3.0.0

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#680]
1. Should we mark `CssInliner` as the new default (instead of as as tech preview) and mark the `Emogrifier` class as deprecated in 3.0?
1. As 3.0 is per semantic-versioning definition a breaking release (and `CssInliner` a tech preview before 3.0), do you think ti would be okay if we removed the automatic removal of invisible nodes from `CssInliner` for 3.0?

**Comment by oliverklee** [comment]
And we have this remark in the `README` anyway:

`$emogrifier->disableInvisibleNodeRemoval()` - By default, Emogrifier removes
  elements from the DOM that have the style attribute `display: none;`.  If
  you would like to keep invisible elements in the DOM, use this option.
  Note: This option will be removed in Emogrifier 3.0. HTML tags with
  `display: none;` then will always be retained.

**Comment by JakeQZ** [comment]
> 1. Should we mark `CssInliner` as the new default (instead of as as tech preview) and mark the `Emogrifier` class as deprecated in 3.0?

I think so.
 
> 2. As 3.0 is per semantic-versioning definition a breaking release (and `CssInliner` a tech preview before 3.0), do you think ti would be okay if we removed the automatic removal of invisible nodes from `CssInliner` for 3.0?

As it's a tech preview before 3.0, we could even remove it for 2.2 (if there is a 2.2) - along the lines of the semantics for pre-1.0 releases (i.e. version 0.2 may include breaking changes from 0.1 though 0.1.1 may not).  And anyway, we have already changed the way `CssInliner` instances are created since 2.1.x, which is a breaking change (`new CssInliner($html)` -> `CssInliner::fromHtml($html)`).

> Note: This option will be removed in Emogrifier 3.0. HTML tags with
`display: none;` then will always be retained.

Though as the `Emogrifier` class will be marked deprecated, we can probably leave it in that class, just remove it from `CssInliner`.
