### ISSUE TITLE
Move the removal of unprocessable tags from CssInliner to HtmlPruner

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#682]
@JakeQZ @zoliszabo I've been thinking about also moving the removal of unprocessable tags from `CssInliner` to `HtmlPruner` before the 2.2.0 release. What do you think?

**Comment by JakeQZ** [comment]
Seems reasonable.  Historically these tags were removed before the emogrification process, but since #652 I don't think it matters much (and in any case, a `HtmlPruner` instance can process the document before and/or after `CssInliner`).  The feature was probably mainly a workaround for the `DOMDocument` limitation fixed by #652, but may be used for other purposes in the wild.

**Comment by oliverklee** [comment]
Now that I think of it, it looks like we don't need the feature of removing the unprocessable tags anymore. (And if a user needs it after all, we probably will here from them once we have deprecated and then removed the `Emogrifier` class.) So I'm going to remove the corresponding functionality from `CssInliner`.
