### ISSUE TITLE
Plan the 3.0.0 release

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#688]
@zoliszabo, @JakeQZ, I'd like to release version 3.0.0 relatively shortly after version 2.2.0 as I'm salivating for these changes (which will come after 3.0.0 for version 4.0.0):

- drop the old `Emogrifier` class and make everything PSR-4-compliant
- drop support for PHP < 7.0 and use all the niceties of PHP 7
- drop support for non-Composer installations

For this, I'd like to postpone some things that currently are planned for the 3.0.0 milestone. Particularly, I'd like to include only these tickets into the 3.0.0 milestone that someone is going to work on in the next few weeks. Does this sound like a good plan?

Could you please have a look at the 3.0.0 tasks and assigns those tasks to you that you'd like to tackle for 3.0.0? I'll do the same and move all non-assigned tasks to a later milestone.

Thanks! :heart:

**Comment by JakeQZ** [comment]
I've added #380 and assigned it to myself.  I think this would be a good test of the new design to iron out any issues (it will be implemented mostly by `HtmlPruner`), and I have a clear solution in mind (which I've already implemented 'locally' for `Emogrifier`).  I'll write up the proposal there soon...

At a quick glance, quite a few issues look like they'd be fixed by `Symfony\Component\CssSelector\CssSelectorConverter` so should just be a case of adding unit tests (I presume we won't be fixing them for the `Emogrifier` class).

**Comment by oliverklee** [comment]
> I presume we won't be fixing them for the `Emogrifier` class

Yes, that's what I would like to propose, too.

**Comment by JakeQZ** [comment]
#544 looks like quite a biggie.  I've looked again and added a comment.  One of the suggested libraries looks worth investigating further, and probably using.  But it will likely be a fair bit of refactoring, plus initial investigation.  So I'd suggest moving that to 4.0.0.

> have a look at the 3.0.0 tasks and assigns those tasks to you that you'd like to tackle for 3.0.0

Ah, I've read that again now.  I honestly don't expect to have that much time available - sorry - so it's difficult to commit in advance.  I think the current list is a reasonable (but ambitious) goal (other than #544), and the low-hanging fruit would be those already fixed by `CssSelectorConverter`.  I wonder whether it's worth keeping the list roughly as-is for now, and re-reviewing closer to the time you would like to release 3.0 (e.g. in half of a 'few weeks')...?

**Comment by oliverklee** [comment]
> I wonder whether it's worth keeping the list roughly as-is for now, and re-reviewing closer to the time you would like to release 3.0 (e.g. in half of a 'few weeks')...?

Yes, let's do this.
