### ISSUE TITLE
Fix disableStyleBlocksParsing() example in readme OR make it work like presented in the readme

### ISSUE THREAD

**Issue by zoliszabo** [MyIntervals/emogrifier#824]
As reported in issue https://github.com/MyIntervals/emogrifier/issues/823, the following code example extracted from the readme does not work:

```
$visualHtml = CssInliner::fromHtml($html)->disableStyleBlocksParsing()
  ->inlineCss($css)->render();
```

Should we fix the example in the readme or make the option setter methods return `$this`? @oliverklee @JakeQZ

**Comment by JakeQZ** [comment]
I'd suggest setter methods should return `$this` (and indeed any other methods that would not otherwise return a value).  Some methods do so already in the new classes, possibly even some setter methods.  It may only be some of the methods that were copied from the legacy `Emogrifier` class that don't.  I think we should be consistent throughout and `return $this` wherever possible/reasonable.

**Comment by oliverklee** [comment]
I agree.
