### ISSUE TITLE
ExpressionErrorException: "*:last-of-type" is not implemented. 

### ISSUE THREAD

**Issue by Pi-George** [MyIntervals/emogrifier#872]
I'm trying to change over from 2.0 to 3.1

old code:
```
$emogrifier = new Emogrifier();
$emogrifier->setHtml($html);
$emogrifier->setCss($this->createCss());
return $emogrifier->emogrify();
```

new code attempted:

`return CssInliner::fromHtml($html)->inlineCss($this->createCss())->render();`

or

```
$domDocument = CssInliner::fromHtml($html)->inlineCss($this->createCss())->getDomDocument();
Emogrifier\HtmlProcessor\HtmlPruner::fromDomDocument($domDocument)->removeElementsWithDisplayNone();
$html = Emogrifier\HtmlProcessor\CssToAttributeConverter::fromDomDocument($domDocument)->convertCssToVisualAttributes()->render();
return $html;
```

Both give me

Symfony\Component\CssSelector\Exception\ExpressionErrorException: "*:last-of-type" is not implemented.

**Comment by zoliszabo** [comment]
Hi @Pi-George,

Thank you for reporting this issue.

Since version 2.1 Emogrifier is using `symfony/css-selector` for translating CSS to XPath instead of the less capable built-in solution we previously had.

Unfortunately `symfony/css-selector` seems to not support this specific selector - see here:
- https://symfony.com/doc/current/components/css_selector.html
  > Not supported: *:first-of-type, *:last-of-type, *:nth-of-type and *:nth-last-of-type (all these work with an element name (e.g. li:first-of-type) but not with the * selector).
- https://github.com/symfony/css-selector/blob/4b85443ab5e269ed8c7554745890726c57bfeb04/XPath/Extension/PseudoClassExtension.php#L87
 
From the top of my head, you have two possible solution:
1. Get rid of the '*:last-of-type' selectors in you CSS (e.g. replace it with more specific `...:last-of-type` selectors)
2. ... or wrap your Emogrifier code in a `try {...} catch($e) {...}` block.

**Comment by JakeQZ** [comment]
> Hi @Pi-George,
> 
> Thank you for reporting this issue.

Ditto.

> Unfortunately `symfony/css-selector` seems to not support this specific selector

This is true; however, I think there are a couple of issues with Emogrifier that come to light regarding handling this specific selector.

What should happen with unsupported selectors is that rules involving them are preserved by Emogrifier and copied to a `<style>` element in the resulting HTML (so that they would still be effective for email clients that support them this way).

This is not happening in this case, because `:last-of-type` is partially supported, and the filtering of which pseudo-classes are supported is currently Boolean (relevant code is at https://github.com/MyIntervals/emogrifier/blob/3.1/src/Emogrifier/CssInliner.php#L593-L598 and https://github.com/MyIntervals/emogrifier/blob/3.1/src/Emogrifier/CssInliner.php#L54-L55 where `:last-of-type` is considered supported - there is no testing of whether the `...-of-type` pseudo-classes are combined with an element type that would currently be required for them to be supported).

Nonetheless, unless 'debug' mode is enabled, Emogrifier should silently ignore any CSS rules with selectors that cannot be converted but which have not been picked up as being 'unsupported' by the above.  This would normally be caught at https://github.com/MyIntervals/emogrifier/blob/3.1/src/Emogrifier/CssInliner.php#L179-L186, but in this case Symfony is throwing a `Symfony\Component\CssSelector\Exception\ExpressionErrorException` rather than `Symfony\Component\CssSelector\Exception\SyntaxErrorException`.
