### ISSUE TITLE
Get version 5.0.0 out of the door

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#878]
Our [yet-to-be-released version 4.0.0](#874) will still support PHP 7.1. However, [PHP 7.1 has alreay reached its end of life as well](https://www.php.net/supported-versions.php).

So I'd like to release a version 5.0.0 shortly after the release of 4.0.0, allowing us to drop support for PHP 7.1 as well (and maybe add support for PHP 8, if we can do that in any way).

What do you think, @JakeQZ, @zoliszabo, @jjriv?

**Comment by zoliszabo** [comment]
Interesting read on this: https://sebastiandedeyne.com/composer-semver-and-underlying-dependency-changes/

**Comment by oliverklee** [comment]
Thanks.

I know this argument, and I agree that raising the required minimum PHP version technically is no breaking change in the semver sense. Still, I'd prefer to now change the required PHP version within the same major version range so all users can still get versions with new bug fixes and features.

**Comment by JakeQZ** [comment]
> Our [yet-to-be-released version 4.0.0](#874) will still support PHP 7.1.

Actually it will still support PHP 7.0 (though marked as deprecated in the release note / changelog).  But as soon as it is released we can drop PHP 7.0 support from `master`.  This should enable us to progress with some Psalm issues that were being held back by having to retain a version of PHPUnit compatible with PHP 7.0 (though a separate question might be: do we actually need to check the unit-testing code with Psalm?).

A view on dropping PHP 7.1 support from `master` might be taken on the basis of whether this continues to hold us up, e.g. for Psalm, or perhaps to be able to support PHP 8.0.

Another question might be: how many websites are still using PHP 7.1?  Those on shared/cloud hosting environments might have issues if their hosting provider does not allow them choose PHP versions.  And even if it does, if they are running multiple websites, and one of those websites still requires PHP 7.1, they may not be able to upgrade - e.g. cPanel only allows one PHP version _per account_.

Note that WordPress still supports PHP 5.6 (although 7.3 is recommended) and has only dropped support for 5.2 though 5.5 in the last 18 months.

And [according to W3Techs](https://w3techs.com/technologies/details/pl-php), as of 11 June (today), 47.7% of websites using PHP are still on version 5 (or below), and of those using PHP 7, 34% are on either 7.0 or 7.1.  (Yes, that means almost two thirds [65.5%] of websites using PHP are running a version that is already end-of-life!  [[In April that figure was over 68%.](https://en.wikipedia.org/wiki/PHP)])

> So I'd like to release a version 5.0.0 shortly after the release of 4.0.0, allowing us to drop support for PHP 7.1 as well (and maybe add support for PHP 8, if we can do that in any way).

You mean allowing us to drop support for PHP 7.1 _from `master`_, moving forwards?

I would be inclined to see if there's a particular need to drop PHP 7.1 support: perhaps due to dependency issues (like Psalm, mentioned above); or if there are changes required for PHP 8.0 that would break things for PHP 7.1; or anything else that might arise.  ([PHP 8.0 is due for release on 26 Nov with RC1 available 17 Sept.](https://wiki.php.net/todo/php80))

Also, if we do find a need to drop PHP 7.1 support, but haven't made any functional improvements (e.g. resolving isses reported by Psalm may well not fix any actual bugs, just make the code base more robust against future changes that could accidentally break something), then I don't see anything wrong with skipping 5.0 entirely (what would be the point of a 5.0 release which has no perceptible improvements but merely drops support for a legacy PHP version?) - PHP skipped 6.0.

> Interesting read on this

I think it's a fair point when it comes to versions of third-party dependencies, but not PHP itself (and not third-party dependencies if a new version constraint would indirectly bump up the minimum PHP version requirement).  I would consider the version of PHP to be akin to the version of the operating system.  If you were developing a Windows application, you wouldn't make a minor or point release that, say, dropped support for Windows 7.  Switching to a newer PHP version is often not straightforward, for the reasons I've already given.

**Comment by oliverklee** [comment]
Okay, I think I need to write this in a way that is less confusing: :-)

- 4.0.0: PHP >= 7.0 supported
- directly after the 4.0.0 release: drop support for PHP 7.0 from master
- 5.0.0: PHP >= 7.1 supported
- directly after the 5.0.0 release: drop support for PHP 7.1 from master
- 6.0.0: PHP >= 7.2 supported
- directly after the 6.0.0 release: drop support for PHP 7.2 from master
- etc.

**Comment by oliverklee** [comment]
> though a separate question might be: do we actually need to check the unit-testing code with Psalm?

It general, yes (as this can catch some errors as well). However, I still have not been able to find a good solution for having both `vimeo/psalm` as well as `psalm/plugin-phpunit` via Phive. So i'm all for only checking `src/` with Psalm for the time being.

Concerning skipping 5.0.0: I'm hesitant about this as a version 5.0.0 would still be more robust than 4.0.0 using the features from higher PHP versions and a newer version of PHPUnit. I'd sill like to have a small release.

**Comment by JakeQZ** [comment]
> Concerning skipping 5.0.0: I'm hesitant about this as a version 5.0.0 would still be more robust than 4.0.0 using the features from higher PHP versions and a newer version of PHPUnit.

OK.  I guess if there are actually some code changes (e.g. using more type annotations, or changes suggested by Psalm), then these might actually fix something even if we've never actually encountered a specific case where they would (as the saying goes: "Just because you can't see it, doesn't mean it's not there").

> I'd sill like to have a small release.

However, I don't at this time see any particular urgency for a release until the PHP 8 release is more imminent (when we would include PHP 8 support), unless continuing to support PHP 7.1 on `master` starts to hinder progress.

**Comment by JakeQZ** [comment]
PHP 8 is due to be released in a week now.  We'll need an Emogrifier release which 'supports' it (i.e., at least with `composer.json` changed).  It will be simpler I imagine for that to be 5.0.0.  See #925

**Comment by oliverklee** [comment]
I have just tagged and published the release.
