### ISSUE TITLE
@-webkit-keyframes animationName not supported

### ISSUE THREAD

**Issue by janmyszkier** [MyIntervals/emogrifier#886]
created a branch with a test that fails:
https://github.com/janmyszkier/emogrifier/tree/jan/2_2_0_css_animation_test

done based on 2.2.0 (which seems to be currently used by magento/magento2 repository):
https://github.com/magento/magento2/blob/2.3/composer.lock#L3670

please provide a fix or doc information on how to avoid this error with emogrifier, so we can alter our code. (mentioning the animation in the readme would also be helpful if not going to be supported)

**Comment by JakeQZ** [comment]
Hi @janmyszkier,

Thanks for reporting, and in particular for providing a test that fails.

I can confirm that your test also fails with the latest Emogirifer version, 4.0.0.

However, if I add `$subject->setDebug(false);` just after `$subject = $this->buildDebugSubject(...);`, the test passes.

I've also played around with adding some CSS before and after the `@-webkit-keyframes` rule, and this appears to be processed and inlined correctly (when 'debug' is `false`).

Could you try your test with the 2.2.0 release but 'debug' set to `false` and see if that makes a difference?

In the medium-term, I think Emogrifier should handle the various 'unsupported' at-rules as it now does for `@font-face` (see #870) so that they end up in the `<style>` element added back in to the resultant HTML.  (There is a possibility that the ordering could be important, e.g. for `@supports`, but a solution to that would be more involved - see #544.)

**Comment by JakeQZ** [comment]
@janmyszkier, FYI, this issue should be fixed by #899 which will preserve `@keyframes` and other at-rules, and will be closed when that is merged, although that fix won't be immediately avaible in a release.  That said, it appears you should be able to turn 'debug' off and/or upgrade to 4.0.0 to avoid the exception.
