### ISSUE TITLE
Change our default branch name away from "master"

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#908]
Let's get rid of the references to slavery.

https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by JakeQZ** [comment]
OMG.  I had not even considered there might be any connotation until I saw the email with a link to this.

The politics and dialectics are complex and I don't want to dwell on them much here (I don't even know what my own opinion is).  I am white British.  I have some black British friends who were born in the UK.  The slave trade has led to a concentration of wealth and power in certain countries in the world, which persists today.  So, in some ways, indirectly, my black British friends _living today_ may have also benefited from it.  Ironic?!?  I fully support the removal of statues.  They should be placed in museums so that we don't forget the past (or allow people come up with conspiricy theories denying it ever happened); but they should certainly not be glorified and put on public display as they have been for the last 150 years or so.

Back to the matter in hand.

The name `master` was a poor choice anyway, it does not convey well what it is.  There are two very good alternatives I can think of:
- `mainline` &ndash; this is used by [Perforce](https://www.perforce.com/solutions/version-control) &ndash; the analogy is (obviously?) a railway track with some branch lines;
- `trunk` &ndash; I see this often used in articles about version control that I find on t'internet &ndash; the analogy is (obviously?) a tree with branches.

> replacing the term ... with a neutral term like "main"

I think `main` would be another not-very-good choice.  Yet again, it doesn't convey an awful lot.  And it already has another use in programming.  It is the enty point in a program in C, Java, and probably many other programming languages.

Questions:
- Can repository owners decide their own name?
- Who gets to vote on what the default should be?

**Comment by oliverklee** [comment]
We can check whether GitHub suggests a new default branch name, and we can look at what other projects do.

**Comment by zoliszabo** [comment]
I am all in for this change. At this point it does not matter what the origin of the `master` keyword is in Git (the "master/slave" versus "master copy" debate), this step has to be made.

Now the real question is what the new name is going to be... I personally would wait a little more until the big ones figure out the new de facto standard: [GitHub](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/), [GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/220906), [git-for-windows](https://github.com/git-for-windows/git/issues/2674), etc. It seems that the main [Git](https://lore.kernel.org/git/CAOAHyQwyXC1Z3v7BZAC+Bq6JBaM7FvBenA-1fcqeDV==apdWDg@mail.gmail.com/) project will be slower to change, but in the end I think it is GitHub who will dictate the new default, not Git. I really hope that the industry can agree on a common new name, instead of 4-5 different ones.

I personally do like `main`, because by using `git checkout ma` + `TAB` key (for autocomplete) the transition is really easy.

**Comment by JakeQZ** [comment]
> I personally do like `main`, because by using `git checkout ma` + `TAB` key (for autocomplete) the transition is really easy.

I just tested this (via SSH) and it does not work for me.  Maybe you have a fancy shell or shell extension?  But wouldn't the same be true for `mainline` (which I think would be much more descriptive)?

> I personally would wait a little more until the big ones figure out the new de facto standard: [GitHub](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/), [GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/220906), [git-for-windows](https://github.com/git-for-windows/git/issues/2674), etc.

Sounds reasonable, but how long (to wait)?  As I understand, the new name will still be a 'default' and repository admins could choose what they like.

**Comment by oliverklee** [comment]
> I just tested this (via SSH) and it does not work for me. Maybe you have a fancy shell or shell extension?

You'll need to install/configure git bash completion. How to do it depends on the OS or the way you've installied Git.

**Comment by oliverklee** [comment]
A case against `trunk`:
https://twitter.com/wa7son/status/1276117760754569216

**Comment by jjriv** [comment]
I'm 100% in favor of ditching the word "master." Personally, I like the word "main" but i'll let the people doing the contributing make the final decision. Thanks for keeping this project going everyone!

**Comment by JakeQZ** [comment]
> 
> 
> A case against `trunk`:
> https://twitter.com/wa7son/status/1276117760754569216

The problem with that argument is that we'd also have to stop using all sorts of words, or internet acronyms, because people might not know what we mean.  And then we stop using language at all, and are reduced to communicating in gestures.

Trunk meaning car boot is very American.  In other parts of the native English-speaking world it does not have that meaning.  It so happens that many non-native speakers learn from American sources.  Yes it is also used for an Elephant trunk, or in medicine referring to the torso.

But why restrict ourselves to an English word anyway?  Isn't that prejudiced?  How about a Spanish or Mandarin word?  They are the most widely spoken languages after all...

**Comment by JakeQZ** [comment]
Apparently, Twitter are going to replace “master”/“slave” with “leader”/“follower”.

[George Floyd: Twitter drops 'master', 'slave' and 'blacklist'](https://www.bbc.co.uk/news/business-53273923)

The quality of journalism in many outlets has not been good: “The terms are frequently used in programming codes” – this implies to me that we secretly communicate to each other using racist language.  They should have said: “The terms are frequently used to represent concepts in software engineering.”  It’s not “codes” it’s “code”, FFS.  And it’s not “programming codes”, it’s “programming languages” or perhaps “software code” or “computer code”.  No-one refers to it generally as “code” if it can be avoided – I thought the industry had already dealt with the issue of it seeming mysterious by using terms like “code”.  Maybe not to journalists…

Back to reality and the “leader”/“follower” suggestion.  In terms of VCS branches, though it may have some merit, it’s nothing that jumps out to me and says “that’s it, that’s obviously what we should use”.

Having thought about it a while, my current suggestion for replacement of “master” is “primary”.  It is quite linguistically neutral (the word comes from Latin) and has parallels in other languages (première, prima, primera, prvi, первый, etc.).

The ability to type `ma` and hit TAB is, I think, of no relevance, and possibly of hindrance to moving out of some kind of programmer stone age.

**Comment by JakeQZ** [comment]
> the word comes from Latin

But perhaps it is [too soon](https://www.urbandictionary.com/define.php?term=too%20soon) after the Roman domination to use such words.

**Comment by oliverklee** [comment]
I've checked a few other projects:
- [PHPUnit](https://github.com/sebastianbergmann/phpunit): no change yet, and no ticket for it yet
- [Twig](https://github.com/twigphp/Twig): `3.x` (i.e., the branch for the next release)
- [Symfony](https://github.com/symfony/symfony): [probably going the same way Twig already has gone](https://github.com/symfony/symfony/issues/37331)
- TYPO3: no final plans yet
- [Composer](https://github.com/composer/composer): [`2.0` (i.e., the next release line)](https://github.com/composer/composer/issues/8991)

(This is WIP … I'll still need to read the articled you have linked.)

**Comment by oliverklee** [comment]
Having read the articles and thinking of my muscle memory, I'd opt for `main`. Would this be something that would work for you, @zoliszabo and @JakeQZ?

**Comment by JakeQZ** [comment]
> Having read the articles and thinking of my muscle memory, I'd opt for `main`. Would this be something that would work for you, @zoliszabo and @JakeQZ?

I've no objections to `main`, I just think there are better alternatives.  But that is just my humble opinion.

**Comment by oliverklee** [comment]
Okay everybody, then let's have a vote so we can get a clearer picture of where we stand. You can vote -1 (oppose), 0 (I would be okay with this, i.e., I would not oppose this), 1 (this looks really good to me).

| new default branch name | @zoliszabo | @JakeQZ  | @oliverklee |
| -------------------------------- | --------------- | -------------- | -------------- |
| 5.0 (will change as needed |                  |                   |                    |
| 5.x (will change as needed |                  |                   |                    |
| main                                 |                     |                    |                   |
| mainline                             |                  |                   |                    |
| next                             |                  |                   |                    |
| trunk                                 |                     |                   |                    |
| primary                             |                  |                   |                    |

**Comment by JakeQZ** [comment]
> You can vote.

Have done.  Not opposed to anything, and I take on board the Twitter discussion about `trunk` so am no longer particularly in favour of that.  You didn't say that decimal points weren't allowed, so I've voiced a tiny opposition to some ideas.  Having to change the branch name with every release strikes me as being a but onerous, and, also, if there is a branch for a specific release, shouldn't there also be a 'mainline'/'trunk' anyway?

**Comment by oliverklee** [comment]
Article by GitHub about changes from their side: https://github.com/github/renaming

**Comment by JakeQZ** [comment]
> 
> 
> Article by GitHub about changes from their side: https://github.com/github/renaming

This strongly sways the argument in favour of `main`, since that's what GitHub is recommending and using.
